version: "3.9"
   
services:
  db:
    build: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
  analytics:
    build: analytics
    volumes:
      - ./notebooks:/notebooks
    ports:
      - "8888:8888"
    depends_on:
      - db
